name: Trigger soccer_pkg dependencies update

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Trigger update workflow in main repository
        run: |
          # Set the required variables
          repo_owner=Blenders-FC
          repo_name=blenders_soccer_pkg
          event_type="update_subtrees"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"
